[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
fs_permissions = [
    { access = "read-write", path = "../../" },
    { access = "read-write", path = "./" },
]


ffi = true


[rpc_endpoints]
opBNBTestnet = "${OP_BNB_TESTNET_RPC}"

[etherscan]
5611 = { key = "${OP_BNB_ETHERSCAN_API_KEY}", url = "https://api-opbnb-testnet.bscscan.com/api" }
